services:
  ollama:
    image: ollama/ollama
    container_name: ollama
    environment:
      - OLLAMA_ORIGINS=app://obsidian.md:*
    ports:
      - "11434:11434"
    volumes:
      - D:\Containers\Ollama:/root/.ollama
    restart: unless-stopped
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: ["gpu"]
    # For older versions of Docker, you might need to use the environment method
    # environment:
    #   - NVIDIA_VISIBLE_DEVICES=all

  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: open-webui
    ports:
      - "8282:8080"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - D:\Containers\OpenWebUI:/app/backend/data
    restart: unless-stopped

  lightrag:
    image: ghcr.io/hkuds/lightrag:latest
    build:
      context: .
      dockerfile: Dockerfile
      tags:
        - ghcr.io/hkuds/lightrag:latest
    ports:
      - "${HOST:-0.0.0.0}:${PORT:-9621}:9621"
    volumes:
      - D:\Containers\Lightrag\rag_storage:/app/data/rag_storage
      - D:\Containers\Lightrag\inputs:/app/data/inputs
      - D:\Containers\Lightrag\config.ini:/app/config.ini
      - D:\Containers\Lightrag\.env:/app/.env
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 10
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      WORKING_DIR: "/app/data/rag_storage"
      INPUT_DIR: "/app/data/inputs"
      HOST: "0.0.0.0"
      PORT: "9621"

volumes:
  open-webui: